// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoIK_NRsyNB19WgsjSeVs1iNNF8YStLpM',
    appId: '1:10768834060:web:943f78cf182dfe825c1829',
    messagingSenderId: '10768834060',
    projectId: 'cfg45-555a6',
    authDomain: 'cfg45-555a6.firebaseapp.com',
    storageBucket: 'cfg45-555a6.firebasestorage.app',
    measurementId: 'G-MDL5TMYX1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcgz-0PqobCyUs2FyzMknJ022VLxvWIFs',
    appId: '1:10768834060:android:c2434471488527925c1829',
    messagingSenderId: '10768834060',
    projectId: 'cfg45-555a6',
    storageBucket: 'cfg45-555a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkL8-u4Y894NQa9MkoXnFK2AQnhrxMkWw',
    appId: '1:10768834060:ios:e2ced4d6c78af1b45c1829',
    messagingSenderId: '10768834060',
    projectId: 'cfg45-555a6',
    storageBucket: 'cfg45-555a6.firebasestorage.app',
    iosBundleId: 'com.example.nofoodwaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkL8-u4Y894NQa9MkoXnFK2AQnhrxMkWw',
    appId: '1:10768834060:ios:e2ced4d6c78af1b45c1829',
    messagingSenderId: '10768834060',
    projectId: 'cfg45-555a6',
    storageBucket: 'cfg45-555a6.firebasestorage.app',
    iosBundleId: 'com.example.nofoodwaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoIK_NRsyNB19WgsjSeVs1iNNF8YStLpM',
    appId: '1:10768834060:web:8aaea960f1de498a5c1829',
    messagingSenderId: '10768834060',
    projectId: 'cfg45-555a6',
    authDomain: 'cfg45-555a6.firebaseapp.com',
    storageBucket: 'cfg45-555a6.firebasestorage.app',
    measurementId: 'G-TPCPM2XT8B',
  );
}
